### PR TITLE
Change Modifications to be its own class

### PR DESCRIPTION
**Pull request by GrmanRodriguez**
This PR changes the way we write modifications in the `urdf-modifiers` library. 

`Modification` is now a class part of `urdfModifiers.core` with methods for adding the different modifications.

A constructor for creating this class from a section of an ini file has also been added.

Below some examples of the changes:

Previous way of creating modifications:

```python
modifications= {}
modifications[utils.geometry.Modification.DIMENSION] = [0.2, utils.geometry.Modification.ABSOLUTE] 
modifications[utils.geometry.Modification.DENSITY] = [2.0, utils.geometry.Modification.MULTIPLIER]
```

New method:
```python
modifications = Modification()
modifications.add_dimension(0.2, absolute=True)
modifications.add_density(2.0, absolute=False)
```

As you can see it is now clearer and the code is cleaner.

cc @CarlottaSartore

### CODE REVIEW

**Comment by traversaro** [comment]
fyi @fabiodinatale

**Review by vvasco — APPROVED** [review]
LGTM!

**Comment by traversaro** [comment]
@GrmanRodriguez @vvasco can we tag the version of the library before this PR as `v0.0.1` or something similar? we have some scripts that use the old modifications API, and while we could refer to specific checkout, it may be easier to refer to a given tag. No release is necessary, just a small tag is ok.

**Comment by vvasco** [comment]
good idea @traversaro thanks

**Comment by vvasco** [comment]
I'm creating a tag `v0.0.1`

**Comment by GrmanRodriguez** [comment]
In that case I'd say first accept #12 since it's non-breaking and adding it to the tag

**Comment by vvasco** [comment]
> In that case I'd say first accept #12 since it's non-breaking and adding it to the tag

I agree. Then after that PR is accepted and merged, we can proceed with the tag.

**Review by AlexAntn — APPROVED** [review]
LGTM!

PR #12 has been merged, so we can create the tag and then merge this PR too.

Great work @GrmanRodriguez !

**Pull request merged**
